FROM node:18-alpine AS dashboard-builder

WORKDIR /app/apps/dashboard

COPY apps/dashboard/package.json apps/dashboard/package-lock.json ./
RUN npm ci

COPY apps/dashboard ./
RUN npm run build

FROM golang:1.24-alpine

RUN apk add --no-cache git bash curl unzip entr make tar

RUN go install github.com/cespare/reflex@latest

ENV PATH="/go/bin:${PATH}"

COPY --from=dashboard-builder /app/apps/dashboard/dist /app/apps/dashboard/dist

CMD ["bash"]
